version: "3"
services:
        elasticsearch:
                image: 'elastic/elasticsearch:7.4.2'
                container_name: 'elasticsearch'
                hostname: 'elasticsearch'
                environment: 
                        - discovery.type=single-node
                ports:
                        - '9200:9200'
                        - '9300:9300'

        kibana:
                image: 'elastic/kibana:7.4.2'
                container_name: 'kibana'
                hostname: 'kibana'
                ports:
                        - '5601:5601'
                depends_on:
                        - elasticsearch
                links:
                        - elasticsearch

        logstash:
                image: 'elastic/logstash:7.4.2'
                container_name: 'logstash'
                hostname: 'logstash'
                links:
                        - elasticsearch
                depends_on:
                        - elasticsearch
                volumes:
                        - ./logstash:/logstash-config
                command: logstash -f /logstash-config/logstash.conf

        jenkins:
                build:
                        dockerfile: Dockerfile
                        context: ./jenkins
                container_name: 'jenkins'
                hostname: 'jenkins'
                ports:
                        - '8080:8080'
                        - '50000:50000'
                links:
                        - logstash
                volumes:
                        - ./jenkins:/var/jenkins_home
